ALTER TABLE "announcements" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "attendances" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "club_members" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "club_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "court_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "federation_accounts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "fees" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "invoice_counters" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "memberships" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "payments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "person_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "person_guardians" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "person_injury_reports" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "person_medical_checkups" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "person_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "person_qualifications" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "person_tags" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "persons" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "registration_guardians" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "registrations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "seasons" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sponsor_contacts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sponsor_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sponsor_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sponsor_payments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sponsors" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "sponsorship_terms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "team_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "team_notes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;